version: '3'

services:
  banco-django:
    image: postgres:12.6
    container_name: banco-django
    restart: unless-stopped
    environment:
      POSTGRES_DB: clientes-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    networks:
          - app-network

  django-app:
        container_name: django-app
        restart: unless-stopped
        environment:
          DJANGO_SETTINGS_MODULE: 'project.settings'
        build: 
          context: back-end-lccv
          dockerfile: ../Dockerfile
    
        command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./back-end-lccv:/code
        ports:
          - "8000:8000"
        depends_on:
          - banco-django
        networks:
          - app-network

networks:
  app-network:
    driver: bridge