# Generated by Django 4.0 on 2021-12-12 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cad', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.fornecedores')),
                ('id_natureza_despesa', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.naturezasdespesa')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
    ]
