# Generated by Django 4.0 on 2021-12-12 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0002_fornecedores_notasfiscais'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosBem',
            fields=[
                ('id_estado_bem', models.AutoField(primary_key=True, serialize=False)),
                ('estado_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SituacoesUsoBem',
            fields=[
                ('id_situacao_uso_bem', models.AutoField(primary_key=True, serialize=False)),
                ('situacao_uso_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('id_item_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItensNotaFiscal',
            fields=[
                ('id_item_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_servico', models.CharField(max_length=100)),
                ('vinculado', models.CharField(max_length=1)),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.notasfiscais')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('id_bem', models.AutoField(primary_key=True, serialize=False)),
                ('tombamento', models.CharField(max_length=10)),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_lim_garantia', models.DateField()),
                ('data_fim_garantia', models.DateField()),
                ('data_inicio_uso', models.DateField()),
                ('observacoes', models.TextField()),
                ('dt_cad', models.DateField(auto_now=True, null=True)),
                ('id_estado_bem', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.estadosbem')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.marcas')),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.notasfiscais')),
                ('id_situacao_uso_bem', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.situacoesusobem')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
    ]
